
language: android
android:
        components:
                - platform-tools
                - build-tools-23.0.1
                - android-23
                - extra-android-m2repository
script:
        - ./gradlew clean build -i --continue
before_install:
        - chmod +x gradlew
branches:
        only:
                - master